In [ ]:
!pip install pandas-profiling
!pip uninstall -y pandas-profiling numba visions
!pip install ydata-profiling

In [3]:
from sklearn.preprocessing import FunctionTransformer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
import pickle

In [8]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("kaggleprollc/phishing-url-websites-dataset-phiusiil")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'phishing-url-websites-dataset-phiusiil' dataset.
Path to dataset files: /kaggle/input/phishing-url-websites-dataset-phiusiil

In [9]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [10]:
df=pd.read_csv("/kaggle/input/phishing-url-websites-dataset-phiusiil/PhiUSIIL_Phishing_URL_Dataset.csv")

In [11]:
df.shape

(235795, 56)

In [12]:
df[df.IsDomainIP==1]

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,TLDLength,NoOfSubDomain,HasObfuscation,NoOfObfuscatedChar,ObfuscationRatio,NoOfLettersInURL,LetterRatioInURL,NoOfDegitsInURL,DegitRatioInURL,NoOfEqualsInURL,NoOfQMarkInURL,NoOfAmpersandInURL,NoOfOtherSpecialCharsInURL,SpacialCharRatioInURL,IsHTTPS,LineOfCode,LargestLineLength,HasTitle,Title,DomainTitleMatchScore,URLTitleMatchScore,HasFavicon,Robots,IsResponsive,NoOfURLRedirect,NoOfSelfRedirect,HasDescription,NoOfPopup,NoOfiFrame,HasExternalFormSubmit,HasSocialNet,HasSubmitButton,HasHiddenFields,HasPasswordField,Bank,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
125,8003080.txt,http://198.98.58.123/,20,198.98.58.123,13,1,123,44.489796,0.444444,0.0,0.001223,3,2,0,0,0.0,0,0.000,10,0.500,0,0,0,3,0.150,0,2,546,0,0,0.0,0.000000,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0
401,8085380.txt,http://43.134.167.94/servicelogin?passive=1209...,191,43.134.167.94,13,1,94,4.813395,0.400000,0.0,0.042737,2,2,0,0,0.0,95,0.497,41,0.215,5,3,0,24,0.168,1,2,199,0,0,0.0,0.617284,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1205,8085364.txt,http://43.128.92.128/servicelogin?passive=1209...,163,43.128.92.128,13,1,128,5.769865,0.444444,0.0,0.046133,3,2,0,0,0.0,85,0.521,29,0.178,4,3,0,19,0.160,1,2,171,0,0,0.0,0.775194,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1362,8085379.txt,http://43.134.167.94/v3/signin/identifier?dsh=...,472,43.134.167.94,13,1,94,1.727385,0.400000,0.0,0.034393,2,2,0,0,0.0,306,0.648,106,0.225,10,1,15,27,0.112,1,125,52992,1,43134167v3signinidentifier?dsh=s151927330%3a16...,0.0,0.000000,0,0,1,1,0,1,0,2,0,0,1,1,0,0,0,0,1,1,0,0,2,0,5,0
2481,8085411.txt,http://43.153.207.103/v3/signin/identifier?dsh...,471,43.153.207.103,14,1,103,1.730846,0.400000,0.0,0.036437,3,2,0,0,0.0,312,0.662,96,0.204,10,1,15,30,0.119,1,125,53042,1,43153207v3signinidentifier?dsh=s-16339560%3a16...,0.0,0.000000,0,0,1,1,0,1,0,2,0,0,1,1,0,0,0,0,1,1,0,0,2,0,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230582,8078580.txt,http://43.134.240.146/v3/signin/identifier?dsh...,319,43.134.240.146,14,1,146,3.058103,0.400000,0.0,0.040543,3,2,0,0,0.0,201,0.630,57,0.179,7,1,0,30,0.119,1,2,1638,1,43134240v3signinidentifier?dsh=s-754639004:167...,0.0,0.000000,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
233569,8093700.txt,http://43.153.207.103/servicelogin?passive=120...,164,43.153.207.103,14,1,103,5.735252,0.400000,0.0,0.045738,3,2,0,0,0.0,85,0.518,30,0.183,4,3,0,19,0.159,1,2,172,0,0,10.0,0.746269,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
233640,8087066.txt,http://49.51.43.12/v3/signin/identifier?dsh=s-...,406,49.51.43.12,11,1,12,1.574377,0.375000,0.0,0.039883,2,2,0,0,0.0,284,0.700,59,0.145,8,1,0,31,0.099,1,2,1638,1,495143v3signinidentifier?dsh=s-1794114331:1679...,0.0,0.000000,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
233868,oph03468.txt,http://43.134.167.94/v3/signin/identifier?dsh=...,264,43.134.167.94,13,1,94,3.222744,0.400000,0.0,0.035107,2,2,0,0,0.0,160,0.606,61,0.231,6,2,0,20,0.106,1,47,452235,1,43134167v3signinidentifier?dsh=s704692612:1671...,0.0,0.000000,0,1,1,1,0,0,0,1,0,0,1,0,0,0,1,0,1,0,1,0,0,0,4,0
233955,oph02027.txt,http://104.14.132.210/,22,104.14.132.210,14,1,210,44.489796,0.400000,0.0,0.001784,3,2,0,0,0.0,0,0.000,11,0.500,0,0,0,4,0.182,0,17,70,0,0,10.0,10.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0

In [13]:
df.columns

Index(['FILENAME', 'URL', 'URLLength', 'Domain', 'DomainLength', 'IsDomainIP',
       'TLD', 'URLSimilarityIndex', 'CharContinuationRate',
       'TLDLegitimateProb', 'URLCharProb', 'TLDLength', 'NoOfSubDomain',
       'HasObfuscation', 'NoOfObfuscatedChar', 'ObfuscationRatio',
       'NoOfLettersInURL', 'LetterRatioInURL', 'NoOfDegitsInURL',
       'DegitRatioInURL', 'NoOfEqualsInURL', 'NoOfQMarkInURL',
       'NoOfAmpersandInURL', 'NoOfOtherSpecialCharsInURL',
       'SpacialCharRatioInURL', 'IsHTTPS', 'LineOfCode', 'LargestLineLength',
       'HasTitle', 'Title', 'DomainTitleMatchScore', 'URLTitleMatchScore',
       'HasFavicon', 'Robots', 'IsResponsive', 'NoOfURLRedirect',
       'NoOfSelfRedirect', 'HasDescription', 'NoOfPopup', 'NoOfiFrame',
       'HasExternalFormSubmit', 'HasSocialNet', 'HasSubmitButton',
       'HasHiddenFields', 'HasPasswordField', 'Bank', 'Pay', 'Crypto',
       'HasCopyrightInfo', 'NoOfImage', 'NoOfCSS', 'NoOfJS', 'NoOfSelfRef',
       'NoOfEmptyRef', 'NoOfExternalRef', 'label'],
      dtype='object')

In [14]:
print(len('https://www.hunksintrunks.co.uk'))

31

In [ ]:
from ydata_profiling import ProfileReport
prof=ProfileReport(df)
prof.to_file(output_file='pandas_profiling.html')

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.drop_duplicates(inplace=True)

In [17]:
df.URL[df.URL.duplicated()].shape

(425,)

In [18]:
for i in df.columns:
  if df[i].dtype=='object':
    print(i,df[i].nunique())

FILENAME 235795
URL 235370
Domain 220086
TLD 695
Title 197874

In [19]:
df.head()

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,TLDLength,NoOfSubDomain,HasObfuscation,NoOfObfuscatedChar,ObfuscationRatio,NoOfLettersInURL,LetterRatioInURL,NoOfDegitsInURL,DegitRatioInURL,NoOfEqualsInURL,NoOfQMarkInURL,NoOfAmpersandInURL,NoOfOtherSpecialCharsInURL,SpacialCharRatioInURL,IsHTTPS,LineOfCode,LargestLineLength,HasTitle,Title,DomainTitleMatchScore,URLTitleMatchScore,HasFavicon,Robots,IsResponsive,NoOfURLRedirect,NoOfSelfRedirect,HasDescription,NoOfPopup,NoOfiFrame,HasExternalFormSubmit,HasSocialNet,HasSubmitButton,HasHiddenFields,HasPasswordField,Bank,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,0.061933,3,1,0,0,0.0,18,0.581,0,0.0,0,0,0,1,0.032,1,558,9381,1,à¸‚à¹ˆà¸²à¸§à¸ªà¸” à¸‚à¹ˆà¸²à¸§à¸§à¸±à¸™à¸™à¸µ...,0.000000,0.000000,0,1,1,0,0,0,0,1,0,0,1,1,0,1,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,0.050207,2,1,0,0,0.0,9,0.391,0,0.0,0,0,0,2,0.087,1,618,9381,1,johannes gutenberg-universitÃ¤t mainz,55.555556,55.555556,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,0.064129,2,2,0,0,0.0,15,0.517,0,0.0,0,0,0,2,0.069,1,467,682,1,voice fm southampton,46.666667,46.666667,0,1,1,0,0,1,0,0,0,0,1,1,0,0,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,0.057606,3,1,0,0,0.0,13,0.500,0,0.0,0,0,0,1,0.038,1,6356,26824,1,home page: seminars in fetal and neonatal medi...,0.000000,0.000000,0,1,1,0,0,0,1,12,0,1,1,1,0,0,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,0.059441,3,1,0,0,0.0,20,0.606,0,0.0,0,0,0,1,0.030,1,6089,28404,1,fundaciÃ³n rewilding argentina,100.000000,100.000000,0,1,1,1,1,1,0,2,0,1,1,1,0,1,1,0,1,244,15,34,72,1,85,1

In [20]:
df.drop(columns=['URL', 'Domain', 'FILENAME', 'Title'], inplace=True)

In [21]:
df.duplicated().sum()

np.int64(808)

In [22]:
df.drop_duplicates(inplace=True)

In [26]:
def tld_bucket(tld):

  high_trust  = {'.com', '.org', '.edu', '.gov', '.net', '.co.uk', '.ac.uk'}
  medium_trust = {'.io', '.co', '.me', '.uk', '.de', '.fr', '.in', '.ca', '.au'}
  low_trust   = {'.xyz', '.top', '.click', '.online', '.site', '.info', '.biz'}
  very_low    = {'.tk', '.ml', '.ga', '.cf', '.gq', '.pw', '.cc'}
  if tld in high_trust:   return 4
  if tld in medium_trust: return 3
  if tld in low_trust:    return 2
  if tld in very_low:     return 1
  return 0

df['TLD_risk'] = df['TLD'].apply(tld_bucket)
df.drop(columns=['TLD'], inplace=True)

In [27]:
df.duplicated().sum()

np.int64(0)

In [28]:
for i in df.columns:
  if df[i].dtype=='object':
    print(i,df[i].nunique())

In [29]:
df.sample(10)

,URLLength,DomainLength,IsDomainIP,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,TLDLength,NoOfSubDomain,HasObfuscation,NoOfObfuscatedChar,ObfuscationRatio,NoOfLettersInURL,LetterRatioInURL,NoOfDegitsInURL,DegitRatioInURL,NoOfEqualsInURL,NoOfQMarkInURL,NoOfAmpersandInURL,NoOfOtherSpecialCharsInURL,SpacialCharRatioInURL,IsHTTPS,LineOfCode,LargestLineLength,HasTitle,DomainTitleMatchScore,URLTitleMatchScore,HasFavicon,Robots,IsResponsive,NoOfURLRedirect,NoOfSelfRedirect,HasDescription,NoOfPopup,NoOfiFrame,HasExternalFormSubmit,HasSocialNet,HasSubmitButton,HasHiddenFields,HasPasswordField,Bank,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label,TLD_risk
24645,21,15,0,65.013774,1.000000,0.522907,0.020771,3,1,0,0,0.0,4,0.190,5,0.238,0,0,0,1,0.048,0,14,1141,1,100.000000,100.000000,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0
111141,45,14,0,28.303303,1.000000,0.522907,0.058238,3,0,0,0,0.0,34,0.756,0,0.000,0,0,0,3,0.067,1,5,53,0,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
25078,29,22,0,100.000000,1.000000,0.522907,0.071594,3,1,0,0,0.0,16,0.552,0,0.000,0,0,0,1,0.034,1,1598,2293,1,85.714286,85.714286,0,1,1,0,0,1,0,0,0,1,1,0,0,0,1,0,1,48,15,18,141,9,157,1,0
234406,76,70,0,13.961871,0.274194,0.000012,0.032061,3,2,0,0,0.0,57,0.750,6,0.079,0,0,0,2,0.026,0,143,213,1,0.000000,0.000000,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,2,0,0,25,0,0
210607,33,26,0,100.000000,1.000000,0.522907,0.053825,3,1,0,0,0.0,20,0.606,0,0.000,0,0,0,1,0.030,1,1226,7335,1,100.000000,100.000000,0,0,0,0,0,1,0,1,0,1,1,1,0,0,1,0,1,69,3,8,81,0,7,1,0
62048,32,25,0,100.000000,1.000000,0.079963,0.060973,3,1,0,0,0.0,19,0.594,0,0.000,0,0,0,1,0.031,1,3254,14083,1,0.000000,0.000000,0,0,1,0,0,1,0,3,0,1,1,1,0,0,1,0,0,41,10,13,165,0,42,1,0
225645,27,20,0,54.119048,0.625000,0.522907,0.045758,3,1,0,0,0.0,16,0.593,2,0.074,0,0,0,2,0.074,0,2,831,0,0.000000,0.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0
43996,31,24,0,100.000000,0.823529,0.001188,0.053277,2,2,0,0,0.0,17,0.548,0,0.000,0,0,0,2,0.065,1,12153,880,1,0.000000,0.000000,1,1,1,0,0,1,0,2,0,1,1,1,0,1,0,0,1,314,7,8,1261,0,1243,1,0
120011,25,19,0,58.444444,0.583333,0.018013,0.063824,2,1,0,0,0.0,12,0.480,0,0.000,0,0,0,2,0.080,0,11,77,1,100.000000,100.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
134039,26,19,0,100.000000,1.000000,0.522907,0.070267,3,1,0,0,0.0,13,0.500,0,0.000,0,0,0,1,0.038,1,496,2657,1,100.000000,100.000000,1,1,1,0,0,0,0,0,1,1,1,0,0,0,0,0,1,4,14,25,35,0,38,1,0

In [30]:
X=df.drop(columns=['label'])
y=df['label']

In [31]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [32]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(187989, 51) (46998, 51) (187989,) (46998,)

In [33]:
preprocess=ColumnTransformer([
    ("num",Pipeline([
        ('scaler',StandardScaler())
    ]),x_train.columns)
])

In [34]:
pipe=make_pipeline(preprocess,LogisticRegression())

In [35]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  Index(['URLLength', 'DomainLength', 'IsDomainIP', 'URLSimilarityIndex',
       'CharContinuationRate', 'TLDLegitimateProb', 'URLCharProb', 'TLDLength',
       'NoOfSubDomain', 'HasObfuscation', 'NoOfObfuscatedChar',
       'ObfuscationRatio', 'NoOfLettersInURL'...
       'Robots', 'IsResponsive', 'NoOfURLRedirect', 'NoOfSelfRedirect',
       'HasDescription', 'NoOfPopup', 'NoOfiFrame', 'HasExternalFormSubmit',
       'HasSocialNet', 'HasSubmitButton', 'HasHiddenFields',
       'HasPasswordField', 'Bank', 'Pay', 'Crypto', 'HasCopyrightInfo',
       'NoOfImage', 'NoOfCSS', 'NoOfJS', 'NoOfSelfRef', 'NoOfEmptyRef',
       'NoOfExternalRef', 'TLD_risk'],
      dtype='object'))])),
                ('logisticregression', LogisticRegression())])

In [36]:
reg_p=pipe.predict(x_test)

In [37]:
reg=classification_report(reg_p,y_test,output_dict=True)
reg_df=pd.DataFrame(reg).transpose()

In [38]:
reg_df

              precision    recall  f1-score       support
0              0.999652  1.000000  0.999826  20123.000000
1              1.000000  0.999740  0.999870  26875.000000
accuracy       0.999851  0.999851  0.999851      0.999851
macro avg      0.999826  0.999870  0.999848  46998.000000
weighted avg   0.999851  0.999851  0.999851  46998.000000

In [39]:
print(df.duplicated().sum())

0

In [40]:
y_train_pred = pipe.predict(x_train)
print("Train Accuracy:", accuracy_score(y_train, y_train_pred))
print("Test Accuracy:", accuracy_score(y_test, reg_p))

Train Accuracy: 0.9999042497167387
Test Accuracy: 0.9998510574918081

In [41]:
scores = cross_val_score(pipe, X, y, cv=10)

print(scores)
print(scores.mean())

[0.99982978 0.99982978 0.99978722 0.99995744 0.99987233 0.99995744
 0.99991489 0.99974466 0.99995744 0.99982977]
0.9998680775006387

In [42]:
# Save the trained SVM model to a file
filename = 'Phish_guard_model.pkl'
pickle.dump(pipe, open(filename, 'wb'))

print(f"SVM model successfully saved to {filename}")

SVM model successfully saved to Phish_guard_model.pkl